spring:
  application:
    name: provider
  main:
    allow-bean-definition-overriding: true
dubbo:
  scan:
    base-packages: com.yuansb.demo.dubbo.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://127.0.0.1:8848